apiVersion: v1
kind: Service
metadata:
  name: {{ include "velld.fullname" . }}-api
  labels:
    {{- include "velld.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "velld.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "velld.fullname" . }}-web
  labels:
    {{- include "velld.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "velld.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
